---
title: "hw4 dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")
```

```{r}
set.seed(1)
rest_sam = 
  rest_inspec %>% 
  filter(
    !is.na(score), 
    boro == "MANHATTAN")%>%
  select(
    dba, action, score, inspection_date,violation_code, record_date,grade,boro,cuisine_description, critical_flag) %>%
   
  sample_n(1000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A:boxplot of the distribution of scores among different cuisine descriptions

```{r}
rest_sam %>%
  filter(
    cuisine_description %in% c("Soups & Sandwiches", "Hotdogs","Bakery","Salads","Steak","Pizza","Seafood"
  ))%>%
  mutate(
    cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(x = ~cuisine_description, y = ~score, color = ~cuisine_description, type = "box")
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B:bar chart of the frequencies of each violation code

```{r}
rest_sam %>%
  count(violation_code)%>%
  mutate(violation_code = fct_reorder(violation_code, n)) %>% 
  plot_ly(x = ~violation_code, y = ~n, type = "bar")
```


### Chart C:violin plot of the distribution of scores in each grade group

```{r}
rest_sam %>%
  plot_ly(
    x = ~grade, y = ~score, type = "violin",
    color = ~grade, alpha = 0.5)
```